version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    groups:
      remix:
        patterns:
        - "@remix-run*"
        - "remix"
      react:
        patterns:
        - "react*"
      mui:
        patterns:
        - "@mui*"
        - "@emotion"
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"
    groups:
      aws-sdk:
        patterns:
        - "github.com/aws/aws*"
        - "github.com/awslabs/aws*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
