version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    groups:
      remix:
        patterns:
        - "react-router"
        - "@react-router*"
        - "remix-auth"
        - "remix-auth-auth0"
      react:
        patterns:
        - "react*"
      mui:
        patterns:
        - "@mui*"
        - "@emotion"
      eslint:
        patterns:
        - "eslint*"
        - "@typescript-eslint/*"
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"
    groups:
      aws-sdk:
        patterns:
        - "github.com/aws/aws*"
        - "github.com/awslabs/aws*"
  - package-ecosystem: "gomod"
    directory: "/scripts"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
