version: 3

tasks:
  start:
    dir: ../scripts/frontend
    desc: run frontend in background
    cmds:
    - go run start.go
  stop:
    dir: ../scripts/frontend
    desc: stop frontend
    cmds: [ go run stop.go ]
  install:
    desc: install dependencies
    cmds: [ npm ci ]
  #  test:
  #    desc: test frontend
  #    env:
  #      CI: true
  #    cmds: [ yarn test ]

  default:
    cmds:
    - task: lint
    - task: prettier
    - task: tsc
#    - task: test
  ci:
    deps: [ install ]
    cmds:
    - npm run build
    - task: lint
    - task: prettier
    - task: tsc
#   - task: test

  build:
    deps: [ install ]
    cmds:
    - rm -rf build
    - npm run build
    - task: zip
  zip:
    dir: build
    cmds: [ zip -r frontend.zip . ]

  lint:
    desc: lint frontend
    cmds: [ npm run lint ]
  prettier:
    desc: format frontend
    cmds: [ npm run prettier ]
  tsc:
    desc: typecheck frontend
    cmds: 
    - npm run build
    - npm run typecheck
    
