version: 3

tasks:
  start:
    dir: ../scripts/frontend
    desc: run frontend in background
    cmds:
    - go run start.go
  stop:
    dir: ../scripts/frontend
    desc: stop frontend
    cmds: [ go run stop.go ]
  install:
    desc: install dependencies
    cmds: [ yarn ]
  test:
    desc: test frontend
    env:
      CI: true
    cmds: [ yarn test ]

  world:
    cmds:
    - task: lint
    - task: test
  ci:
    deps: [ install ]
    cmds:
    - task: test

  build:
    cmds:
    - yarn
    - REACT_APP_DOMAIN_NAME={{.REACT_APP_DOMAIN_NAME}} REACT_APP_CLIENT_ID={{.REACT_APP_CLIENT_ID}} REACT_APP_API_ENDPOINT=https://api.{{.REACT_APP_DOMAIN_NAME}} yarn build
    - aws s3 cp ../frontend/build s3://music-rating-deployment-bucket-frontend --recursive --profile music-rating

  lint:
    desc: lint frontend
    cmds: [ yarn lint ]