version: 3

tasks:
  default:
    cmds:
    - task: lint
    - task: tsc
#    - task: test
    - task: build

  start:
    dir: ../scripts/frontend
    desc: run frontend in background
    cmds:
    - go run start.go
    env:
      API_ENDPOINT: "http://127.0.0.1:8080"
  stop:
    dir: ../scripts/frontend
    desc: stop frontend
    cmds: [ go run stop.go ]
  install:
    desc: install dependencies
    cmds: [ npm ci ]
    sources:
    - package-lock.json
    generates:
    - node_modules/**/*
  test:
    desc: test frontend
    cmds: [ npm run test ]

  build:
    deps: [ install ]
    cmds:
    - npm run build
    - task: zip
  zip:
    dir: build/server
    cmds: [ zip -r ../frontend.zip . ]

  lint:
    deps: [ task: build ]
    cmds: [ npm run lint ]
  tsc:
    cmds: [ npm run typecheck ]
  prettier:
    cmds: [ npm run prettier ]

  ci:
    deps: [ install ]
    cmds:
    - task: lint
    - task: tsc
#    - task: test
    - task: build
