language: node_js
dist: bionic
node_js:
  - "10"

branches:
  only:
    - master

before_install:
  - touch src/aws-exports.js

before_script:
  - cd amplify/backend/function/artistInformationService/src
  - yarn
  - yarn test

cache: yarn