version: '3'

includes:
  aws:
    taskfile: aws/
    dir: aws/
  frontend:
    taskfile: frontend/
    dir: frontend/
  backend:
    taskfile: backend/
    dir: backend/

tasks:
  deploy:
    desc: Build and deploy frontend and backend
    deps: [ backend:build, frontend:build ]
    cmds:
    - task: aws:deploy-to-aws