version: '3'

includes:
  aws:
    taskfile: aws/
    dir: aws/
  frontend:
    taskfile: frontend/
    dir: frontend/
  backend:
    taskfile: backend/
    dir: backend/

tasks:
  start:
    desc: Start the project
    cmds:
    - task: frontend:start
    - task: backend:start
  stop:
    desc: Stop everything
    cmds:
    - task: frontend:stop
    - task: backend:stop
  install:
    desc: Install all dependencies
    cmds:
    - task: frontend:install
    - task: backend:install
  default:
    desc: Verify and test everything
    cmds:
    - task: frontend
    - task: backend

  deploy:
    desc: Build and deploy frontend and backend
    deps: [ backend:build, frontend:build ]
    cmds:
    - task: aws:deploy