version: "2"

formatters:
  enable:
  - goimports
  - golines
  - gci
  - gofmt

  settings:
    golines:
      max-len: 180

linters:
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - canonicalheader
  - copyloopvar
  - cyclop
  - depguard
  - dupl
  - durationcheck
  - embeddedstructfieldcheck
  - errcheck
  - errname
  - errorlint
  - exhaustive
  - exptostd
  - fatcontext
  - forbidigo
  - funcorder
  - funlen
  - gocheckcompilerdirectives
  - gochecknoglobals
  - gochecknoinits
  - gochecksumtype
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godoclint
  - godot
  - gomoddirectives
  - goprintffuncname
  - gosec
  - govet
  - iface
  - ineffassign
  - intrange
  - iotamixing
  - loggercheck
  - makezero
  - mirror
  - mnd
  - modernize
  - musttag
  - nakedret
  - nestif
  - nilerr
  - nilnesserr
  - nilnil
  - noctx
  - nolintlint
  - nonamedreturns
  - nosprintfhostport
  - perfsprint
  - predeclared
  - promlinter
  - protogetter
  - reassign
  - recvcheck
  - revive
  - rowserrcheck
  - sloglint
  - spancheck
  - sqlclosecheck
  - staticcheck
  - testableexamples
  - testifylint
  - testpackage
  - tparallel
  - unconvert
  - unparam
  - unqueryvet
  - unused
  - usestdlibvars
  - usetesting
  - wastedassign

  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0

    depguard:
      rules:
        "deprecated":
          files:
          - "$all"
          deny:
          - pkg: github.com/golang/protobuf
            desc: Use google.golang.org/protobuf instead, see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
          - pkg: github.com/satori/go.uuid
            desc: Use github.com/google/uuid instead, satori's package is not maintained
          - pkg: github.com/gofrs/uuid$
            desc: Use github.com/gofrs/uuid/v5 or later, it was not a go module before v5
        "non-test files":
          files:
          - "!$test"
          deny:
          - pkg: math/rand$
            desc: Use math/rand/v2 instead, see https://go.dev/blog/randv2
        "non-main files":
          files:
          - "!**/main.go"
          deny:
          - pkg: log$
            desc: Use log/slog instead, see https://go.dev/blog/slog

    embeddedstructfieldcheck:
      empty-line: false
      forbid-mutex: true

    errcheck:
      check-type-assertions: true

    exhaustive:
      check:
      - switch
      - map

    exhaustruct:
      exclude:
      - ^net/http.Client$
      - ^net/http.Cookie$
      - ^net/http.Request$
      - ^net/http.Response$
      - ^net/http.Server$
      - ^net/http.Transport$
      - ^net/url.URL$
      - ^os/exec.Cmd$
      - ^reflect.StructField$
      - ^github.com/Shopify/sarama.Config$
      - ^github.com/Shopify/sarama.ProducerMessage$
      - ^github.com/mitchellh/mapstructure.DecoderConfig$
      - ^github.com/prometheus/client_golang/.+Opts$
      - ^github.com/spf13/cobra.Command$
      - ^github.com/spf13/cobra.CompletionOptions$
      - ^github.com/stretchr/testify/mock.Mock$
      - ^github.com/testcontainers/testcontainers-go.+Request$
      - ^github.com/testcontainers/testcontainers-go.FromDockerfile$
      - ^golang.org/x/tools/go/analysis.Analyzer$
      - ^google.golang.org/protobuf/.+Options$
      - ^gopkg.in/yaml.v3.Node$
      allow-empty-returns: true

    funcorder:
      struct-method: false

    funlen:
      lines: 100
      statements: 50

    gochecksumtype:
      default-signifies-exhaustive: false

    gocognit:
      min-complexity: 20

    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false

    godoclint:
      enable:
      - no-unused-link
      - require-stdlib-doclink

    govet:
      enable-all: true
      disable:
      - fieldalignment

    inamedparam:
      skip-single-param: true

    mnd:
      ignored-functions:
      - args.Error
      - flag.Arg
      - flag.Duration.*
      - flag.Float.*
      - flag.Int.*
      - flag.Uint.*
      - os.Chmod
      - os.Mkdir.*
      - os.OpenFile
      - os.WriteFile
      - prometheus.ExponentialBuckets.*
      - prometheus.LinearBuckets

    nakedret:
      max-func-lines: 0

    nolintlint:
      allow-no-explanation: [ funlen, gocognit, golines ]
      require-explanation: true
      require-specific: true

    perfsprint:
      strconcat: false

    reassign:
      patterns:
      - ".*"

    revive:
      rules:
      - name: var-naming
        severity: warning
        disabled: false
        exclude: [ "" ]
        arguments:
        - [ "API", "ID", "URL" ]
        - []
        - - skip-package-name-checks: true

    rowserrcheck:
      packages:
      - github.com/jmoiron/sqlx

    sloglint:
      context: scope

    staticcheck:
      initialisms: [ "ACL", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "SIP", "RTP", "AMQP", "DB", "TS" ]
      checks:
      - -ST1000

    usetesting:
      os-temp-dir: true

  exclusions:
    rules:
    - text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      linters: [ govet ]
