version: 3

tasks:
  install:
    cmds:
    - task: install-golangci-lint
    - task: dynamodb:install
  start:
    desc: Start the backend locally
    deps: [ dynamodb:start ]
    dir: ../scripts/backend
    cmds:
    - go run start.go
  stop:
    desc: Stop the backend locally
    deps: [ dynamodb:stop ]
    dir: ../scripts/backend
    cmds:
    - go run stop.go
  default:
    desc: Format and test everything
    cmds:
    - task: format
    - task: lint
    - task: test
  build:
    cmds:
    - GOOS=linux GOARCH=amd64 go build -mod=vendor -o out/bootstrap cmd/api/main.go
    - zip -j out/backend.zip out/bootstrap
  test:
    desc: run tests without caching the results
    deps: [ dynamodb:start ]
    dir: internal/
    cmds:
    - go clean -testcache
    - go test ./...
  ci:
    deps: [ install ]
    cmds:
    - task: test
  format:
    desc: format code
    cmds:
    - go fmt ./...

  lint:
    desc: run linter on sources
    cmds: [ ../scripts/third_party/golangci-lint/golangci-lint run ./... ]

  dynamodb:install:
    dir: ../scripts
    cmds:
    - go run dynamodb/download.go
  dynamodb:start:
    desc: start local dynamodb
    dir: ../scripts/dynamodb
    cmds:
    - go run start.go
  dynamodb:stop:
    desc: stop local dynamodb
    dir: ../scripts/dynamodb
    cmds:
    - go run stop.go

  install-golangci-lint:
    dir: ../scripts
    cmds:
    - go run golangci_lint/download.go