AWSTemplateFormatVersion: '2010-09-09'
Description: MusicRating Deployment Utils
Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: music-rating-deployment-bucket
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
  DeploymentBucketNameParameter:
    Type: AWS::SSM::Parameter
    DependsOn: DeploymentBucket
    Properties:
      Description: Deployment Bucket Name
      Name: '/deployment-bucket/name'
      Type: String
      Value: !Ref DeploymentBucket
  DeploymentBucketDomainNameParameter:
    Type: AWS::SSM::Parameter
    DependsOn: DeploymentBucket
    Properties:
      Description: Deployment Bucket Regional Domain Name
      Name: '/deployment-bucket/regional-domain-name'
      Type: String
      Value: !GetAtt [ DeploymentBucket, RegionalDomainName ]
  DeploymentUser:
    Type: AWS::IAM::User
    Properties:
      UserName: MusicRating-Deployment
      Policies:
      - PolicyName: deployment
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 's3:PutObject'
            Resource: !Sub
            - ${BucketArn}/bootstrap.zip
            - { BucketArn: !GetAtt [ DeploymentBucket, Arn ] }
      - PolicyName: services
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'apigateway:*'
            - 'cloudformation:*'
            - 'cloudfront:*'
            - 'cognito-idp:*'
            - 'dynamodb:*'
            - 'iam:*'
            - 'lambda:*'
            - 'route53:*'
            - 'ssm:*'
            - 's3:*'
            Resource: '*'
