AWSTemplateFormatVersion: '2010-09-09'
Description: MusicRating Deployment Utils
Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: music-rating-deployment-bucket
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      LifecycleConfiguration:
        Rules:
        - NoncurrentVersionExpirationInDays: 7
          Status: Enabled
  DeploymentBucketNameParameter:
    Type: AWS::SSM::Parameter
    DependsOn: DeploymentBucket
    Properties:
      Description: Deployment bucket name
      Name: '/music-rating/deployment-bucket/name'
      Type: String
      Value: !Ref DeploymentBucket

  # Frontend
  StaticAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: music-rating-static-assets
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      LifecycleConfiguration:
        Rules:
        - NoncurrentVersionExpirationInDays: 7
          Status: Enabled
  StaticAssetsBucketNameParameter:
    Type: AWS::SSM::Parameter
    DependsOn: StaticAssetsBucket
    Properties:
      Description: Static assets bucket name
      Name: '/music-rating/static-assets-bucket/name'
      Type: String
      Value: !Ref StaticAssetsBucket
  StaticAssetsBucketDomainNameParameter:
    Type: AWS::SSM::Parameter
    DependsOn: StaticAssetsBucket
    Properties:
      Description: Static assets bucket Regional Domain Name
      Name: '/music-rating/static-assets-bucket/regional-domain-name'
      Type: String
      Value: !GetAtt [ StaticAssetsBucket, RegionalDomainName ]

  # Deployment-User
  DeploymentUser:
    Type: AWS::IAM::User
    Properties:
      UserName: MusicRating-Deployment
      Policies:
      - PolicyName: services
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'apigateway:*'
            - 'cloudformation:*'
            - 'cloudfront:*'
            - 'cognito-idp:*'
            - 'dynamodb:*'
            - 'events:*'
            - 'iam:*'
            - 'lambda:*'
            - 'route53:*'
            - 'ssm:*'
            - 's3:*'
            Resource: '*'
