AWSTemplateFormatVersion: '2010-09-09'
Description: MusicRating Deployment Utils
Resources:
  DeploymentBucketBackend:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: music-rating-deployment-bucket-backend
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE

  # Frontend
  DeploymentBucketFrontend:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: music-rating-deployment-bucket-frontend
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
  DeploymentBucketFrontendNameParameter:
    Type: AWS::SSM::Parameter
    DependsOn: DeploymentBucketFrontend
    Properties:
      Description: Frontend Deployment Bucket Name
      Name: '/deployment-bucket-frontend/name'
      Type: String
      Value: !Ref DeploymentBucketFrontend
  DeploymentBucketFrontendDomainNameParameter:
    Type: AWS::SSM::Parameter
    DependsOn: DeploymentBucketFrontend
    Properties:
      Description: Frontend Deployment Bucket Regional Domain Name
      Name: '/deployment-bucket-frontend/regional-domain-name'
      Type: String
      Value: !GetAtt [ DeploymentBucketFrontend, RegionalDomainName ]

  # Deployment-User
  DeploymentUser:
    Type: AWS::IAM::User
    Properties:
      UserName: MusicRating-Deployment
      Policies:
      - PolicyName: services
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'apigateway:*'
            - 'cloudformation:*'
            - 'cloudfront:*'
            - 'cognito-idp:*'
            - 'dynamodb:*'
            - 'events:*'
            - 'iam:*'
            - 'lambda:*'
            - 'route53:*'
            - 'ssm:*'
            - 's3:*'
            Resource: '*'

  # FestivalBands
  DeploymentBucketFestivalBands:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: festival-bands-deployment-bucket
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
  FestivalBandsDeploymentBucket:
    Type: AWS::SSM::Parameter
    DependsOn: DeploymentBucketFestivalBands
    Properties:
      Description: Deployment bucket name for FestivalBands lambdas
      Name: /festival-bands/deployment-bucket/name
      Type: String
      Value: !Ref DeploymentBucketFestivalBands
