AWSTemplateFormatVersion: "2010-09-09"
Description: MusicRating Domain
Parameters:
  ParamDomainName:
    Type: String

Resources:
  DomainHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref ParamDomainName
  DomainHostedZoneParameter:
    Type: AWS::SSM::Parameter
    DependsOn: DomainHostedZone
    Properties:
      Description: MusicRating HostedZone Id
      Name: !Sub '/domain/${ParamDomainName}/hosted-zone'
      Type: String
      Value: !Ref DomainHostedZone