AWSTemplateFormatVersion: "2010-09-09"
Description: MusicRating Domain
Parameters:
  ParamDomainName:
    Type: String

Resources:
  DomainHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref ParamDomainName
  DomainHostedZoneParameter:
    Type: AWS::SSM::Parameter
    DependsOn: DomainHostedZone
    Properties:
      Description: MusicRating HostedZone Id
      Name: !Sub '/domain/${ParamDomainName}/hosted-zone'
      Type: String
      Value: !Ref DomainHostedZone

  DomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref ParamDomainName
      DomainValidationOptions:
      - DomainName: !Ref ParamDomainName
        HostedZoneId: !Ref DomainHostedZone
      SubjectAlternativeNames:
      - !Sub '*.api.${ParamDomainName}'
      ValidationMethod: DNS
  DomainCertificateParameter:
    Type: AWS::SSM::Parameter
    DependsOn: DomainCertificate
    Properties:
      Description: MusicRating certificate ARN
      Name: !Sub '/domain/${ParamDomainName}/certificate'
      Type: String
      Value: !Ref DomainCertificate