version: 3

tasks:
  deploy:
    cmds:
    - aws cloudformation deploy --template-file cloudformation.yml --stack-name MusicRating-App --capabilities CAPABILITY_IAM
      --parameter-overrides
      ParamDomainName={{.REACT_APP_DOMAIN_NAME}}
      ParamBackendVersion={{.BACKEND_VERSION_ID}}
      ParamDeploymentBucketFrontendDomainName=/deployment-bucket-frontend/regional-domain-name
      ParamDeploymentBucketFrontendName=/deployment-bucket-frontend/name
      ParamDomainHostedZoneId=/domain/{{.REACT_APP_DOMAIN_NAME}}/hosted-zone
      ParamEUDomainCertificateArn=/domain/api.{{.REACT_APP_DOMAIN_NAME}}/certificate
      ParamClientId={{.REACT_APP_CLIENT_ID}}
      ParamFestivalBucketName=/festival-bucket/name
      ParamFestivalBucketArn=/festival-bucket/arn
      --profile music-rating
    vars:
      BACKEND_VERSION_ID:
        sh: aws s3api put-object --bucket music-rating-deployment-bucket-backend --key backend.zip --body ../backend/out/backend.zip --profile music-rating | jq -r .VersionId