AWSTemplateFormatVersion: "2010-09-09"
Description: Creates the hosted zone
Parameters:
  ParamHostedZoneName:
    Type: String
  env:
    Type: String

Resources:
  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: !Ref ParamHostedZoneName
