name: Deploy
on:
  push:
    branches:
    - main
permissions:
  contents: read

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install Task
      uses: arduino/setup-task@v1
    - name: test
      run: task frontend:test

  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Test
      run: task backend:test

  deploy:
    concurrency: deploy
    needs: [test-frontend, test-backend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy
      run: |
        aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile music-rating
        aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" --profile music-rating
        REACT_APP_DOMAIN_NAME="$DOMAIN_NAME" REACT_APP_CLIENT_ID="$CLIENT_ID" task deploy
      env:
        DOMAIN_NAME: ${{secrets.DOMAIN_NAME}}
        CLIENT_ID: ${{secrets.CLIENT_ID}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEFAULT_REGION: eu-west-1
